import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./scss/global.scss";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<Navbar />
					<div className="max-w-7xl mt-4 mx-auto rounded-xl overflow-hidden">
						{children}
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
